import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken'; import {validationResult} from 'express-validator'; import User from '../models/User.js';
import Trip from '../models/Trip.js';
import {verifyFirebaseIdToken} from '../config/firebaseAdmin.js';
const publicUser=user=>({id:user.id,name:user.name,email:user.email,createdAt:user.createdAt}); const token=user=>jwt.sign({id:user.id},process.env.JWT_SECRET,{expiresIn:'7d'});
export async function register(req,res,next){try{const e=validationResult(req);if(!e.isEmpty())return res.status(400).json({success:false,message:e.array()[0].msg});const {name,email,password}=req.body;if(await User.exists({email:email.toLowerCase()}))return res.status(409).json({success:false,message:'Email already registered'});const user=await User.create({name,email,password});res.status(201).json({success:true,data:{user:publicUser(user),token:token(user)}});}catch(x){next(x)}}
export async function login(req,res,next){try{const {email,password}=req.body;const user=await User.findOne({email:email?.toLowerCase()}).select('+password');if(!user||!await bcrypt.compare(password||'',user.password)){console.warn(`[AUTH] login rejected at ${new Date().toISOString()} (invalid credentials)`);return res.status(401).json({success:false,message:'Invalid email or password'});}console.info(`[AUTH] login accepted at ${new Date().toISOString()}`);res.json({success:true,data:{user:publicUser(user),token:token(user)}});}catch(x){console.error(`[AUTH] login failed: ${x.message}`);next(x)}}
export async function googleLogin(req,res,next){try{const e=validationResult(req);if(!e.isEmpty())return res.status(400).json({success:false,message:'A Firebase ID token is required'});const decoded=await verifyFirebaseIdToken(req.body.idToken);const email=decoded.email?.toLowerCase();if(!email||decoded.email_verified!==true)return res.status(401).json({success:false,message:'Google account must provide a verified email'});let user=await User.findOne({$or:[{googleUid:decoded.uid},{email}]});if(user){if(!user.googleUid){user.googleUid=decoded.uid;await user.save();}}else{const name=typeof decoded.name==='string'&&decoded.name.trim()?decoded.name.trim():email.split('@')[0];user=await User.create({name,email,googleUid:decoded.uid,authProvider:'google'});}console.info(`[AUTH] Google login accepted at ${new Date().toISOString()}`);res.json({success:true,data:{user:publicUser(user),token:token(user)}});}catch(x){if(['auth/argument-error','auth/id-token-expired','auth/id-token-revoked','auth/invalid-id-token'].includes(x.code))return res.status(401).json({success:false,message:'Firebase identity token is invalid or expired'});if(['app/invalid-credential','app/credential-internal-error'].includes(x.code))return res.status(503).json({success:false,message:'Firebase Admin credentials are not configured on the server'});console.error(`[AUTH] Google login failed: ${x.code||x.name}`);next(x)}}
export async function me(req,res,next){try{const user=await User.findById(req.userId);if(!user)return res.status(404).json({success:false,message:'User not found'});res.json({success:true,data:publicUser(user)});}catch(x){next(x)}}
export async function deleteMyData(req,res,next){try{const result=await Trip.deleteMany({userId:req.userId});res.json({success:true,data:{deletedTrips:result.deletedCount}});}catch(x){next(x)}}
