// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWqaZUdWudrLeFF4boG6bWv4jvqqc2hrc',
    appId: '1:101345389497:web:dfa4f578f1ebe56d1ae468',
    messagingSenderId: '101345389497',
    projectId: 'carbonfootprint-15615',
    authDomain: 'carbonfootprint-15615.firebaseapp.com',
    storageBucket: 'carbonfootprint-15615.firebasestorage.app',
    measurementId: 'G-MEWG5LW7ZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiZvnnN0LmrcYh5V48cZvwA1Wn1_lvMaI',
    appId: '1:101345389497:android:d73332f50bd36d301ae468',
    messagingSenderId: '101345389497',
    projectId: 'carbonfootprint-15615',
    storageBucket: 'carbonfootprint-15615.firebasestorage.app',
  );
}
